### ISSUE TITLE
GetLines() throws an exception using foreach

### ISSUE THREAD

**Issue by rocky05475** [madelson/MedallionShell#13]
I'm getting "Collection was modified; enumeration operation may not execute".

**Comment by madelson** [comment]
@rocky05475 can you please provide:

1. The full exception message and stack trace (basically the output of exception.ToString())

2. The relevant code you are using, and some description of the data you are expecting to see from GetLines()?

Thanks!

**Comment by rocky05475** [comment]
I got confused. It's happening when I do this:

var lines = new List();

Command.Run("myapp"...).RedirectTo(lines).RedirectStandardErrorTo(lines);

foreach (var line in lines)...


בתאריך יום ו׳, 23 ביוני 2017 ב-15:02 מאת madelson <notifications@github.com

**Comment by madelson** [comment]
@rocky05475 ok I see the issue. There are two.

First, you at redirecting your output to the lines list and then enumerating that list before the command finishes. Thus, the list is being added to as you are enumerating it. Either call command.Wait() before the foreach, or do the foreach on command.StandardOutput.GetLines().Concact(command.StandardError.GetLines()) instead of redirecting to a List. 

Second, you are redirecting two streams to the same list. Since List is not threadsafe, you can hit issues if both streams add to the list at the same time. Either use a thread-safe collection or redirect to separate lists and combine them at the end. Alternatively, the streaming Concat solution mentioned above solves this by avoiding List altogether.

Hope that helps!
-Mike

**Comment by rocky05475** [comment]
The thing is that I would like to use GetLines() "on the fly", while the
process is still running...

בתאריך יום ו׳, 23 ביוני 2017 ב-21:57 מאת madelson <notifications@github.com

**Comment by madelson** [comment]
This is addressed by the fix to #14
