### ISSUE TITLE
Add an overload to pass arguments as string

### ISSUE THREAD

**Issue by rocky05475** [madelson/MedallionShell#15]
And bypass syntax thing when using this overload. 

Very important feature!

**Comment by madelson** [comment]
Hi @rocky05475. This should be possible today using the StartInfo option:

Command.Run("exe", new object[0], options: o=>o.StartInfo(s=>s.Arguments="..."))

I'm hesitant to offer a direct overload for this since it is an advanced use-case. It would need a different name than Run because otherwise it would be indistinguishable from the existing Run overloads. 

Another option could be to add a Parse method to WindowsCommandLineSyntax so that you could parse the argument string and then feed it to the exisiting API.

**Comment by rocky05475** [comment]
Ok. Seems fair enough :)

By the way, how can I pass more than one property to StartInfo?

בתאריך שבת, 24 ביוני 2017 ב-15:27 מאת madelson <notifications@github.com>:

**Comment by madelson** [comment]
rocky05475 you can either call .StartInfo() multiple times or you can pass a multi line lambda to one call:

```
.StartInfo(s => {
    s.Arguments = ...;
    s.Verb = ...;
}
```
