### ISSUE TITLE
Expose PID without using Command.Process.Id

### ISSUE THREAD

**Issue by rocky05475** [madelson/MedallionShell#16]
Because I want to use the DisposeOnExit feature and still get the PID.

**Comment by madelson** [comment]
@rocky05475 I guess the concern I have is that DisposeOnExit is supposed to be used when you are treating the process like a function call and not interacting with it as it runs. If you care about the PID, you probably don't want to use DisposeOnExit() since this means you want to interact with it.

Once a process exits, PID is meaningless because it could be assigned to another process.

Can you explain the use-case of wanting to use these features together?

**Comment by rocky05475** [comment]
This is connected to my issue about killing process tree.
I'm using TASKILL to kill them.
That's why I need the PID :)

בתאריך יום ב׳, 26 ביוני 2017 ב-14:28 מאת madelson <notifications@github.com
