### ISSUE TITLE
Interacting with long running processes

### ISSUE THREAD

**Issue by Wintereise** [madelson/MedallionShell#23]
Hi,

We're considering using MedallionShell to interact with what is essentially a daemon process that will never really "finish."

We'd like to keep the handle open and interact with it as needed, however, the methods in the documentation seem mostly suited towards one off commands that will eventually finish.

Does MedallionShell support what we're trying to do? If yes, are there any examples available anywhere?

I apologize for opening this as an issue on the repo , but I couldn't really find documentation for this.

Thank you.

**Comment by madelson** [comment]
Hi @Wintereise , thanks for your interest in the library!

It's true that MedallionShell is most commonly used for processes which terminate after completing some work. However, it can (and has) been used to interact with long-running processes as well.

Some things to consider:
* MedallionShell redirects standard output and standard error by default. It then proceeds to auto-consume and buffer those streams to avoid having the external process deadlock. For a long-running process, if the process is writing to these streams but not consuming them then this would create a memory leak. You can easily prevent this by either (a) consuming the streams (e. g. redirecting them to Console.Out) or (b) preventing them from being redirected in the first place using the `StartInfo` option when creating the `Command`.
* Obviously, you wouldn't want to specify a process timeout (there is no timeout by default).
* If you need to interact with the underlying `Process` object, you'll want to specify `options.DisposeOnExit(false)` so that accessing the `Command.Process` property is safe.

The only thing I can think of that really isn't supported is creating a `Command` from a `Process` that is already running as opposed to using MedallionShell to start a new process. This would come up if you were interacting with a true daemon process that was already running before your program started. If this is indeed what you're trying to do, I'd be interested in understanding more about your use-case to see whether adding an API like `Command.FromExistingProcess()` would be valuable.

Let me know if you have other questions or are running into issues!

**Comment by Wintereise** [comment]
@madelson Many thanks for providing insight. I'll give it a try shortly and let you know.

As to `The only thing I can think of that really isn't supported is creating a Command from a Process that is already running as opposed to using MedallionShell to start a new process. `, we're not trying to do that either.

The daemon will be started and managed by C# code.

**Comment by Wintereise** [comment]
@madelson One question, is it possible to attach callbacks to the stdout/stderr streams somehow that are called every time lines are produced?

If not, what is your recommendation to consuming them interactively? (We care about the data on stdout and need to act based on what's produced, continuously)

**Comment by madelson** [comment]
@Wintereise there are a bunch of ways to consume lines interactively, although event-based is not one of them. I personally dislike the event-based solution as the threading model gets complicated quickly; it's hard to guarantee that events for subsequent lines are processed serially (or at least serially enough for the given use-case). Another problem with events is that when shutting down the process there's no way to be sure when the last event handler has finished, creating race conditions. Events also don't offer an obvious way to recover from errors.

In my opinion the best approach here is using simple async loop to consume the stream:

```
string line;
while ((line = await command.StandardOutput.ReadLineAsync().ConfigureAwait(false)) != null)
{
    ProcessLine();
}
```

This gives you fine-grained control over serial/parallel processing: if you want to go parallel just have ProcessLine() launch a background thread.

You can easily launch this loop in a background thread as well:

```
var consumeStandardOutputTask = Task.Run(() => ConsumeStandardOutputAsync(command));
```

If you need to shut down the process, you can await the loop task to make sure that all lines have been consumed. You can handle errors either with a try-catch insider the loop or at the top level by awaiting or continuing on the loop task.

**Comment by Wintereise** [comment]
Thank you so much for the insight!

**Comment by madelson** [comment]
Closing for now, but feel free to keep posting if you have questions or run into issues.
