### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by Andrew-Hanlon** [madelson/MedallionShell#5]
This library looks very useful, but I am extremely leery of the operator overloading. C# operators are defined to have specific meanings, and changing their meaning solely in the context of this library makes the code much less readable (even for someone who knows shell scripting). I would recommend using a fluent syntax instead (`x.Pipe()`, `x.Redirect()`, etc.). Clearly only my two cents.

**Comment by madelson** [comment]
Thanks for the feedback.

I completely understand that perspective. Note that the library does offer method calls to accomplish the same goals in a slightly more verbose way:

``` C#
var cmd = Command.Run(...);
cmd.StandardOutput.PipeToAsync(...);
```

Looking over the API, though, it is true that the specific semantics of the operators; returning a wrapper Command object which encapsulates both the command and the redirection task isn't exposed. I'll plan to add Pipe() and Redirect() methods in the next release so that those who dislike the operators will never be required to use them.

Removing the operators would be a breaking change, so I'd rather leave them in for now and see if I get more feedback of this flavor/wait until I am motivated to make a different breaking change and do this at the same time.

**Comment by madelson** [comment]
I've added new fluent methods to remove any need to use the operator overloads.
