### ISSUE TITLE
Passing arugments in the form of --argument="output"

### ISSUE THREAD

**Issue by arendvw** [madelson/MedallionShell#55]
What passing arguments to medallion shell I can only seem to be able to get parse "--command=output", rather than the common form --command="output".

Is this a possibility in medallion shell, or this way of passing arguments not supported?

**Comment by madelson** [comment]
@arendvw all interpretation of the command line is done by the process receiving the arguments.

When constructing a command line, there is a first level parsing step which is "tokenization", or breaking up the command line into a list of strings. MedallionShell performs escaping so that each separate string/object you pass in the arguments list will be seen as a separate token by the process being invoked.

In the example you give, `--command=output` is actually one token from the command line syntax perspective. So you should be able to pass this by doing `new[] { "--command=output" }` in MedallionShell.

Let me know if that doesn't work!
