### ISSUE TITLE
Timeout reached as part of the CommandResult

### ISSUE THREAD

**Issue by DavidFlamme** [madelson/MedallionShell#60]
Hello,

it would be nice to have the information if the timeout was reached and the process had to be killed. For example a bool called TimeoutReached as part of the CommandResult.

**Comment by madelson** [comment]
@DavidFlamme thanks for reaching out.

If the timeout is reached, you will not get a command result at all. Instead `Command.Task` should fault with a `TimeoutException`. You should also see this exception if you try to access `Command.Result`, which waits for `Command.Task` internally. Are you seeing otherwise, can this be used for what you're trying to do?

**Comment by madelson** [comment]
@DavidFlamme closing this since it seems answered; feel free to post again if you still are having issues.
