### ISSUE TITLE
Pass arguments without escaping

### ISSUE THREAD

**Issue by masaeedu** [madelson/MedallionShell#7]
It doesn't appear the library provides any way to disable escaping. I need to pass plain old arguments.

**Comment by madelson** [comment]
EDIT:

The easiest way to do this is to use the StartInfo() option to set the arguments directly:

```
var command = Command.Run("foo.exe", options: o => o.StartInfo(si => si.Arguments = "my argument string"));
```

ORIGINAL RESPONSE:

@masaeedu you should be able to do this by setting your own `CommandLineSyntax`. Something like this:

```
class SingleArgumentStringSyntax : CommandLineSyntax
{
    public string CreateArgumentString(IEnumerable<string> arguments)
    {
        var argumentsArray = arguments.ToArray();
        if (argumentsArray.Length != 1) { throw new ArgumentException(nameof(arguments), "must have exactly one argument"); }

        return argumentsArray[0];
    }
}
```

Here's how to use it:

```
var command = Command.Run("foo.exe", new[] { "my argument string" }, options: o => o.Syntax(new SingleArgumentStringSyntax()));
```

If you're doing this a lot, you could capture these options in an instance of the `Shell` class and use that throughout your application.

This is definitely a workaround; I'm interested to know more about your use-case. It seems like this is potentially something that MedallionShell should support directly. For example, it would be nice to be able to do:

```
var command = Command.Run("foo.exe", options: o => o.StartInfo(si => si.Arguments = "my argument string"));
```

Thoughts?

**Comment by masaeedu** [comment]
@madelson Your final snippet is what I ended up doing. As far as the override behavior is concerned, I don't like using inheritance to extend built in functionality, since I have no idea what invariants the method I'm overriding is supposed to obey, or how it interacts with the other members of the class. It would be ideal if we could just supply a `Func` for `CreateArgumentString`, or if that is awkward, perhaps `CommandLineSyntax` could be substituted with an interface `ICommandLineSyntax` for users to implement.

**Comment by madelson** [comment]
@masaeedu good call that my second snippet actually works fine, which means that the workaround isn't required.

As far as CommandLineSyntax, this is actually intended to be an extension point for consumers. If you look at the source/intellisense [here](https://github.com/madelson/MedallionShell/blob/master/MedallionShell/CommandLineSyntax.cs), you can see that the class and method behavior are well-documented.

The reason that this is implemented as an abstract class instead of a Func or interface is because abstract classes can be changed in the future without breaking binary backwards compatibility (since new virtual methods can be added).
