### ISSUE TITLE
Threading problem, locks other instance files

### ISSUE THREAD

**Issue by tomasr78** [madelson/MedallionShell#90]
I have found a lock file issue with MedallionShell when it is running several threads. 

For example, I run two command-line applications (`App1`, `App2`) using the code below and pass two different files for each app (`App1 -> File1`, `App2 -> File2`)

Sometimes, the `App1 -> File1` finish processing the file, but for an unknown reason, File1 is locked by the App2 app.
It is not possible to read the File1 file until App2 exits, through File1 was executed with App1 app in the first Command.Run instance.

Any idea what is going on? Is the code below thread-safe?

```
 var command = Command.Run(MyApp,
                    new[] {MyFile},
                    options => options
                        .Timeout(new TimeSpan(0, 0, 0, Conversion.Timeout))
                        .CancellationToken(Conversion.CancellationToken));

                try
                {
                    command.Wait();
                }
                catch (TimeoutException)
                {
                    throw new MyException(...);
                }

                if (!command.Result.Success)
                    switch (command.Result.ExitCode)
                    {
                        //Report exception
                    }
```

**Comment by tomasr78** [comment]
I have found that this problem exists when UseShellExecute is set to False.

**Comment by madelson** [comment]
Hi @tomasr78 it's going to be hard to figure out more without more information. For example:
* What are App1 and App2? A known program or something you wrote? What do they each do?
* Can you show the full code that kicks off both commands? The code shown kicks off 1 command
* What happens if you use `Process` rather than MedallionShell?

This seems unlikely to be a MedallionShell issue because in the code shown MedallionShell doesn't touch the file at all; it just passes the name of the file as a command line argument.

**Comment by tomasr78** [comment]
Sorry for the confusion, the problem is related to Magick.NET library which uses CreateProcess under the hood to run ImageMagick. It seems their CreateProcess interacts with other CraeteProcess methods and produce file lock problems. 
The problem described here https://github.com/dlemstra/Magick.NET/issues/1054

**Comment by madelson** [comment]
@tomasr78 thanks for the update. Do you think this issue can be closed?

**Comment by tomasr78** [comment]
The issue is related to handles inheritance if you are not yet familiar with the problem you can read more at https://github.com/dotnet/runtime/issues/13943

Do you have any plans to improve your library to fix the issue?

**Comment by madelson** [comment]
@tomasr78 I've had https://github.com/madelson/MedallionShell/issues/54 filed for some time.

The problem is that AFAIK there's not really any way to do that without abandoning the `Process` class entirely and reimplementing everything using P/Invoke (let me know if you disagree). 

Thus far, I've been waiting for .NET to offer a solution which MedallionShell can then adopt.
